### ISSUE TITLE
maxItems option and single selects

### ISSUE THREAD

**Issue by davekaro** [miguelcobain/ember-cli-selectize#10]
This commit https://github.com/miguelcobain/ember-cli-selectize/commit/a4da1677e8f6406b4877071a94f86c29c0e7ad68 made maxItems default to null. Selectize defaults this to 1. I'm not sure if setting maxItems=1 for single selects or maxItems=null (or whatever number) for multiple selects makes more sense. What do you think? 

In any case, something should be added to the README explaining how to use.

**Comment by davekaro** [comment]
I created a PR - https://github.com/miguelcobain/ember-cli-selectize/pull/11

**Comment by miguelcobain** [comment]
Thanks.
If you have time, add a line or two about this in the README, please.
