### ISSUE TITLE
Know from which select you come

### ISSUE THREAD

**Issue by OutOfNutella** [miguelcobain/ember-cli-selectize#101]
Hello there !

Is there any way to know from which select you come from when an action is sended by select-item ?

I'll explain a bit my problem : I have differents select using ember-selectize in my page. Their content is loaded dynamically, even their ids. 
So, when I'll choose an option in one select, I want my action in my controller to know from which select you come from (something about the id of my select)

I tried something which worked well in your addon : 

```
Ember.run.schedule('actions', this, function() {
      var value = this.get('value');
      var id = this.get('id');
      this.sendAction('select-item', selection, value, id);
      this.sendAction('select-value', value);
});
```

Have you ever thought to implement this or is there a solution to send extra parameter to an action ?

Thx for your answer

**Comment by MarSik** [comment]
This would be useful for multiple events.. create-item being one of them. I have basically a "shopping cart" where you can add lines. Each line has a selectize instance in it. It is possible to create a new item by using the create feature, but I would like to be able to select it immediately. But I can't do that because I do not know which selectize instance sent the event.

**Comment by OutOfNutella** [comment]
Well, I have a little solution to this.

Upgrade your ember to 1.13 in order to have the new action helper : http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html#toc_the-code-action-code-helper

Then, you can call your own action into ember-selectize helper with your own extra parameters, like this 
```
{{#each properties key="@index" as |property|}}
   {{ember-selectize
      id = property
      content = contentFromMyComponent
      optionValuePath = "content.id"
      optionLabelPath = "content.display"
      placeholder = "Select a thing"
      select-item=(action 'selectThing' property)
   }}
{{/each}}
```
Here, I've a list of 'properties' which are datas inserted by my user. I don't know what is the name of the property inserted by him, so that's why each select have differents ids which are the name of the field added. 

In my component, I catch the event sent by my ember-selectize like that : 
```
actions : {
   selectThing: function(property, selection, value) {
       // property extra parameter is the first parameter
       // selection and value parameters are parameters sent by ember-selectize component
   }
}
```

Hope it helps
