### ISSUE TITLE
Not possible to keep selection order when using create-item action

### ISSUE THREAD

**Issue by kevinansfield** [miguelcobain/ember-cli-selectize#102]
When using the `create-item` action to add new items to the selection/content array respecting DDAU there's no way to know _where_ in the selection array the user wanted to enter their shiny new item.

I ran into this issue and made a quick fix to the `_create` method as seen here - https://github.com/kevinansfield/Ghost/commit/06892cce42eae1badf6ef6e3888b83cadb610c44

I'll whip up a PR soon as it seems this extra bit of info is needed to make any use of selectize's caret functionality (unless I'm missing something, please tell me if I am!).

**Comment by miguelcobain** [comment]
@kevinansfield Sending the current caret index seems helpful to me.

A PR with the fix you proposed, along with a README update would be awesome!

**Comment by kevinansfield** [comment]
Cleaning up my old issues. Feel free to re-open if still relevant 🙂
