### ISSUE TITLE
Love love love love love this addon

### ISSUE THREAD

**Issue by toranb** [miguelcobain/ember-cli-selectize#103]
@miguelcobain I just wanted to drop you a quick line to say "thank you" for building such a great addon! I'm using ember 1.13.6 w/ plans to migrate to 2.0 soon and this project is great!

Thanks for supporting it / growing a test driven addon / helping others build great products!

**Comment by toranb** [comment]
Note for anyone watching -upgraded to ember 2.0.1 and this thing was rock solid :)

**Comment by miguelcobain** [comment]
Thanks, @toranb! An honor. :smiley:
