### ISSUE TITLE
Does "ember-cli-selectize" support standalone?

### ISSUE THREAD

**Issue by kirubasankars** [miguelcobain/ember-cli-selectize#109]
Does "ember-cli-selectize" support standalone?

**Comment by miguelcobain** [comment]
By "standalone" you mean a version which doesn't use ember-cli, i.e a globals version?

**Comment by kirubasankars** [comment]
Yes. I am not using ember cli. Can I use ember-cli-selectize?

**Comment by miguelcobain** [comment]
Unfortunately not. :cry: 

Good news is that ember-cli-selectize is just a single component and a single js file.
It should be difficult to port it yourself. We're using some ES6 with babel right now. You might want to transpile it through babel first.

Ideally, we should make this addon use [ember-giftwrap](https://github.com/ef4/ember-giftwrap).

**Comment by kirubasankars** [comment]
:(

Let me port it. Thanks you for immediate response.
