### ISSUE TITLE
Does this support the typeahead remote feature of the core selectize library?

### ISSUE THREAD

**Issue by toranb** [miguelcobain/ember-cli-selectize#111]
I love the library - just curious if the ember addon has support/for remote typeahead search (multiselect for example). If so do you know of a demo/example app showing this off?

**Comment by namlook** [comment]
I'm interested as well. I can't find any references of this in the code...

**Comment by miguelcobain** [comment]
Are you guys referring to "remote source loading"?
Please consider #81

**Comment by namlook** [comment]
yes, exactly :) Maybe a note in the documentation would prevent the same question coming back over and over ?
