### ISSUE TITLE
Passing value to template

### ISSUE THREAD

**Issue by IAmJulianAcosta** [miguelcobain/ember-cli-selectize#116]
Hi, I want to know how to access option in a template, I tried with {{option}}, {{item}} and {{parameter-name}} but nothing works.

How can I do this?

Thank you :)

**Comment by miguelcobain** [comment]
@IAmJulianAcosta Sorry for the delay.

What do you mean by "how to access option in a template"? What template are you refering to?

**Comment by IAmJulianAcosta** [comment]
NP

I need to pass a parameter to a template when rendering using optionTemplate, but I don't know how to do that

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-cli-selectize/commit/47bfcaa9a8470b3f3b845a6e7b64f9272a4cad71

The right way now is to use components. You can use the property `{{data}}` in them. Refer to the README.
