### ISSUE TITLE
Selectize.js error: html.replace is not a function when using optionFunction

### ISSUE THREAD

**Issue by eriklharper** [miguelcobain/ember-cli-selectize#124]
I'm customizing the display of selectize options with the `optionFunction` parameter and I get this error:

```
selectize.js:3106 Uncaught TypeError: html.replace is not a function
```

My usage looks like this:

template:
```
{{ember-selectize
  content=interestSearchResults
  optionFunction=getOption
  optionValuePath="content.id"
  optionLabelPath="content.name"
  filter=searchFilter
  prompt="Search interests"
  searchConjunction="or"
  loading=searchingInterests
  selection=selectedInterest
  select-item="addInterest"
  update-filter="filterInterests"
  }}
```

component `getOption` function:
```
getOption(data, escape) {
    data.label = `<span>${data.label}</span><span style="color: #333; text-align:'right'">${data.data.audienceSize}; people</span>`;
    console.log(data);
    return data;
  },
```

The selectize functions just fine without the `optionFunction` handler.  Because this error happens in selectize.js itself, I wonder if its a bug within that instead of ember-cli-selectize?  not sure.

**Comment by miguelcobain** [comment]
@eriklharper If you check the README closely:
> These functions are expected to build the desired html and return it as a string.

So, you must return a string from the function, not an object. :)

Additionally, you might want to check [ember-power-select](http://www.ember-power-select.com). It is the way forward and I'm also contributing there.

**Comment by eriklharper** [comment]
Thanks, this was exactly my issue!
