### ISSUE TITLE
Is it possible to set the tabindex for this component?

### ISSUE THREAD

**Issue by nnblack1980** [miguelcobain/ember-cli-selectize#132]
Trying to set the tabindex on the component doesn't seem to work. Any advice?

**Comment by miguelcobain** [comment]
@nnblack1980 Looks like selectize.js doesn't support it.
Here is the relevant PR: https://github.com/selectize/selectize.js/pull/302

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-cli-selectize/pull/139
