### ISSUE TITLE
ember-getowner-polyfill

### ISSUE THREAD

**Issue by stebru** [miguelcobain/ember-cli-selectize#142]
I believe this should be added as a dependency, not dev-dependency?

**Comment by mike-north** [comment]
The way that supports node 0.12 (still supported by ember-cli) involves installing the dependent addon explicitly in a consuming app. Dependency works if you're on a much more modern version of node, but addons should aim to support everyone. 

We just need a line [here](https://github.com/miguelcobain/ember-cli-selectize/blob/master/blueprints/ember-cli-selectize/index.js#L11) like this

```js
return this.addBowerPackageToProject('selectize', 'miguelcobain/selectize.js#master').then(function() {
  return this.addAddonToProject('ember-getowner-polyfill', '^1.0.0');
});
```

**Comment by miguelcobain** [comment]
I've always done this through `dependencies` entry in `package.json`. E.g https://github.com/cibernox/ember-power-select/blob/master/package.json#L69

**Comment by mike-north** [comment]
@miguelcobain I believe you'll run into problems if there's an installation blueprint or something else ember-addon-ish, on whatever you're declaring a dependency on. I don't believe that addons are resolved hierarchically all the way down into nested nested nested node_modules (remember, this is the npm2 world I'm talking about :) ). With NPM 3 and a flat node_modules, the world is a little simpler, but we still have to support 0.10 and 0.12.
 
Hence, adding as an NPM dependency is *sometimes* safe, adding as a consuming app dependency (assuming the consumer performs the conflict resolution between versions according to what's most appropriate for them) is *almost always* safe.

For other related discussion around introducing this same addon as a nested addon to another project see: https://github.com/runspired/ember-gestures/pull/44 https://github.com/runspired/ember-gestures/pull/46
