### ISSUE TITLE
Trouble with Async-Search

### ISSUE THREAD

**Issue by talhaobject90** [miguelcobain/ember-cli-selectize#149]
I am trying to make async search working with my rails api. I figured out some way from the documentation and the search is working .              

```
//This is the .hbs code
 {{ember-selectize
                content=selectizeproducts
                optionValuePath="content.id"
                optionLabelPath="content.productname"
                selection=orderitem.product
                placeholder="Select a Product"
                update-filter="searchProduct"
                filter=term
               }}

// in actions
actions:{
// the function with is passed in "update-filter"
      searchProduct(term) {
            var controller = this;
            if (Ember.isBlank(term)) { return []; }
//the query is returning data well.
            controller.store.query('product',{filter:{productname: this.get('term')}}).then(function(pro){
// i am setting the 'selectizeproducts' , the problem is as soon as the products is set the first product sits in the search text area and doesn't let me search again
              controller.set('selectizeproducts',pro);
             });
          },
}

```
This is how it looks like before typing
![samplebefore](https://cloud.githubusercontent.com/assets/7547924/16033178/3a92954c-3228-11e6-87c8-c172dc2fb77d.png)

and immediately after i typed q  the data is populated to the options and i cannot search anymore without hiting backspace.

![sampleafter](https://cloud.githubusercontent.com/assets/7547924/16033269/bc4eb5f2-3228-11e6-8f3b-3c8d22c81eaa.png)

 
![afterselect](https://cloud.githubusercontent.com/assets/7547924/16033180/3d5a2ace-3228-11e6-9754-8819875e0fb0.png)

Is there any better solution or a fix for this problem. May be there is a default way to leave the search text box as left and add some delay to the search. But i cannot figure it out from the docs, please help
Thanks in advance

**Comment by miguelcobain** [comment]
What is the value of `orderitem.product`? Isn't there a selection assigned, so ember-cli-selectize selects it once it is available from options.

**Comment by talhaobject90** [comment]
Sorry, there is no selection in the beginining.
I asked a similar question  [here](https://github.com/cibernox/ember-power-select/issues/545)

**Comment by talhaobject90** [comment]
Can you give me any working examples for asyn-search in hasmany objects loop. That could be really helpful.

**Comment by miguelcobain** [comment]
Did you close this because you solved the problem?

**Comment by talhaobject90** [comment]
Sorry brother, what should i do when no one is ready to give some working code sample. 
Even people are building their products with ember 2.x , they are not willing to share their working codes ,so that newbies could learn best practices from it. 

I have been asking for some examples every where , no reply , 
Then what ? close it and do some other business. :(
