### ISSUE TITLE
[discussion] non object selection

### ISSUE THREAD

**Issue by salzhrani** [miguelcobain/ember-cli-selectize#16]
selection property is usually a single value, but selectize expects an object has has a value path and a label path. What is the proper way to handle this situation.

**Comment by miguelcobain** [comment]
Currently not possible, but definitely doable!

**Comment by topaxi** [comment]
I got the same problem from switching a plain select to selectize... :/

**Comment by miguelcobain** [comment]
This is a top priority.

**Comment by davekaro** [comment]
Maybe I'm not understanding, but this works for me saving the US State on an account object. `state` is just a string field on account. `states` is an array of strings:

    {{ember-selectize
      content=states
      optionValuePath="content"
      optionLabelPath="content"
      selection=account.state
      placeholder="Select State" }}

**Comment by topaxi** [comment]
Yes this works, but not if states is an array of objects of which you only want to select a property as value.
For example states is an array of objects with an property "name" which is a string. Then you wouldn't be able to bind the variable to the name, it would bind to the whole object.

**Comment by miguelcobain** [comment]
@davekaro didn't occur to me passing just `content` to `optionValuePath`. Nice.

@topaxi, conceptually that makes sense to me.
A `selection` **must be** an element of `content`.

In the example you gave, what would be expected? To bind `optionLabelPath` to the selection? It's weird.

Could you post an example of Ember.Select that would do what you expect?
It would be easier for us to understand.

**Comment by topaxi** [comment]
I'm using a bound query param to filter a result set. This means, the parameter is only the id, not an whole object.

```
{{view 'select'
  prompt = 'Filter customer'
  id = 'customer'
  class = 'form-control'
  content = customers
  value = customerId
  optionLabelPath = 'content.name'
  optionValuePath = 'content.id'
  }}
```

I expected that I could just swap view 'select' with ember-selectize but this didn't work out.
I guess the value path should bind to the selection (or value in case of single value selections?), like the Ember.Select view.
It was quite simple to switch out select views which selected whole objects though :+1:

**Comment by miguelcobain** [comment]
I think I nailed the problem.
After reading [the docs](http://emberjs.com/api/classes/Ember.Select.html) it seems that Ember.Select provides both `value` and `selection` bindings.
`selection` will have the selected object. `value` will have the selected value.

We currently only support `selection`. So, I'm assuming that adding support for `value` would be enough to cover your use case, right?

**Comment by topaxi** [comment]
Yes that would totally cover my case, not sure about @salzhrani though.

**Comment by salzhrani** [comment]
I agree

**Comment by miguelcobain** [comment]
@topaxi Any idea on what happens to `value` when selection is multiple?

**Comment by miguelcobain** [comment]
Quoting Ember Select source:

>In single selection mode (when `multiple` is `false`), value can be used to
    get the current selection's value or set the selection by it's value.
    **It is not currently supported in multiple selection mode.**

**Comment by topaxi** [comment]
It seems to be an array though: http://emberjs.jsbin.com/hovonohude/1/

**Comment by topaxi** [comment]
But in any case, single value solves our issue and covers the official ember documentation so i guess it should be fine :)

**Comment by miguelcobain** [comment]
Updated to `0.0.11`.
This should be working for single values. Just bind `value` property.

Also, the default valuePath and labelPath are now `content`, so this:

```handlebars
{{ember-selectize
  content=states
  optionValuePath="content"
  optionLabelPath="content"
  selection=account.state
  placeholder="Select State" }}
```

becomes this

```handlebars
{{ember-selectize
  content=states
  selection=account.state
  placeholder="Select State" }}
```

**Comment by topaxi** [comment]
very nice thanks a lot! :)
