### ISSUE TITLE
`closeAfterSelect` option

### ISSUE THREAD

**Issue by martinmaillard** [miguelcobain/ember-cli-selectize#17]
Several options available in Selectize are not settable on the `ember-selectize` component. The one I need right now is `closeAfterSelect`. Is there a technical reason for it not to be available, or would it be possible to add it ?

**Comment by miguelcobain** [comment]
Looks like that property landed on selectize 11 days ago.
It's perfectly doable.

Keep in mind that you can add any option yourself by overriding the computed property `selectizeOptions` (maybe I should add this to the README).

**Comment by martinmaillard** [comment]
Oops, my bad, I did not realize it was a recent addition.
