### ISSUE TITLE
hideSelected and multiple don't work together

### ISSUE THREAD

**Issue by kswilster** [miguelcobain/ember-cli-selectize#173]
when using the `multiple` option with `ember-selectize`, selected options will always be hidden regardless of the value of `hideSelected`. This is broken as of version 0.5.6. [this ember-twiddle](https://ember-twiddle.com/da1348a77be91f42c56ee05233cc4813?openFiles=twiddle.json%2C) demonstrates the behavior

**Comment by miguelcobain** [comment]
@kswilster thanks for reporting this bug. It should be fixed in version `0.5.8`.
