### ISSUE TITLE
Move selectize and sifter from Bower to NPM

### ISSUE THREAD

**Issue by broerse** [miguelcobain/ember-cli-selectize#183]
@Panman8201 If you have more time please also take a look at this addon. We use sifter separate from this addon too so perhaps we need an `ember-cli-sifter` to fix this. Not sure on this.

**Comment by Panman8201** [comment]
Hehe, don't think I'll be able to hit all addons with bower deps. But if I get time... I couldn't find a `ember-cli-sifter` either..

**Comment by rwwagner90** [comment]
We no longer rely on bower here 😄

**Comment by broerse** [comment]
@rwwagner90 Thanks!
