### ISSUE TITLE
Using multiple=true with ember-changeset-validations

### ISSUE THREAD

**Issue by nchoch** [miguelcobain/ember-cli-selectize#187]
Hello,
I'm currently working on a project using both **ember-cli-selectize** and **ember-changeset-validations** and am wondering if there is a trick into validating the selectize element when using `multiple=true`. I'm looking to validate the presence of one or more selections in the element. The single select mode is currently working fine. Here's an example template of where I'm running into issues: 
```
{{#form.element label="Valid Choices" property="validChoices"
                    useIcons=false as |el|}}
      {{ember-selectize
        content=choices
        optionValuePath="content.id"
        optionLabelPath="content.name"
        selection=changeset.pickedChoices
        multiple=true
        placeholder="Valid Choices"}}
{{/form.element}}
```
I have defined `pickedChoices` in the model with a `hasMany('choice')` relationship. Apart from validation not occurring I'm also receiving an error to use an array with multiple. I can only get the error to disappear if I remove `changeset.` from the selection variable and define `pickedChoices` as an array in the .js file of the component. I'm not sure if this is a selectize or changeset issue, but any direction would be greatly appreciated!

**Comment by miguelcobain** [comment]
@nchoch it's not really a direct answer to the problem, but did you consider using ember-power-select? ember-power-select.com

**Comment by nchoch** [comment]
@miguelcobain Yes and I was running into similar problems validating multiple selection. Think I should be looking at ember-changeset-validations then?

**Comment by nchoch** [comment]
I switched to **ember-power-select** as you suggested and eventually came up with this hacky solution to check for presence. My apologies if this isn't the relevant place to post this, but I thought I'd just follow through on this issue.
```
{{#if changeset.pickedChoice}}
    {{#form.element label="Valid Choices" validation="success"
                    useIcons=false as |el|}}
      {{#power-select-multiple searchField="name" options=choices
                               selected=changeset.pickedChoice
                               onchange=(action (mut changeset.pickedChoice))
                               as |choice|}}
         {{choice.name}}
      {{/power-select-multiple}}
    {{/form.element}}
    
{{else}}

    <label class="custom-error">Valid Choices</label>
    {{#form.element validation="error" useIcons=false as |el|}}
      {{#power-select-multiple searchField="name" options=choices
                               selected=changeset.pickedChoice
                               onchange=(action (mut changeset.pickedChoice))
                               as |choice|}}
         {{choice.name}}
      {{/power-select-multiple}}
      <span class="custom-error">At least one choice must be present</span>
    {{/form.element}}
{{/if}}
```
There are now two nearly identical form elements, but one with `validation="success"` and one with `validation="error"`. The page will simply use the pre-set passing form element if any selections have been made, and otherwise use the pre-set failing form element if no selections have been made. The downside to this is that there is no neutral state to present to a user. For this problem I've implemented the styling class `custom-error` where I've specified my own color for the label and message. Unfortunately, I could not get this technique to work using **ember-cli-selectize**. 
### A note to anyone who may use this: I have not verified the integrity of data passed this way yet using ember-changeset.
