### ISSUE TITLE
Fix breaking changes in FastBoot 1.0

### ISSUE THREAD

**Issue by simonihmig** [miguelcobain/ember-cli-selectize#193]
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

**Comment by rwwagner90** [comment]
Since we're using fastboot-transform now, this should be resolved.
