### ISSUE TITLE
DEPRECATION

### ISSUE THREAD

**Issue by alejandrodevs** [miguelcobain/ember-cli-selectize#197]
When I run `ember server` (Ember CLI: 2.18.0) the console throws a deprecation like this:

```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/admin/Projects/project/node_modules/ember-cli-selectize/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
```

Looks like `ember-cli-version-checker` dev dependency need to be upgraded to "^2.0.0".

**Comment by rwwagner90** [comment]
This is not a direct dep of this addon, and we recently updated some deps, so this should be resolved soon, with a new release.
