### ISSUE TITLE
ember-cli-selectize v0.0.15 npm package is missing index.js (main node entry point)

### ISSUE THREAD

**Issue by xomaczar** [miguelcobain/ember-cli-selectize#24]
Please update npm registry with appropriate fixes.

**Comment by miguelcobain** [comment]
I have no idea what happened.

**Comment by miguelcobain** [comment]
Probably related: https://github.com/npm/npm/issues/5082

**Comment by miguelcobain** [comment]
It is fixed now. Updated my npm. Probably a bug.

**Comment by xomaczar** [comment]
Great, thanks for a quick fix/response
