### ISSUE TITLE
remote searching

### ISSUE THREAD

**Issue by piotrpalek** [miguelcobain/ember-cli-selectize#25]
Does this component support remote searching?

**Comment by miguelcobain** [comment]
Please check this issue, and specifically my comment: https://github.com/miguelcobain/ember-selectize/issues/18#issuecomment-47552253
That is the deprecated repository of the same addon when it wasn't an ember-cli addon.

Basically we delegate that "remote search" logic to another layer (the controller).
Keep in mind that a view is only responsible for representing data, nothing else.
A view shouldn't be doing things like fetching remote records on a server.

Tell me if you have any issues, please..

**Comment by piotrpalek** [comment]
I had the same thoughts as you in that issue you posted and was already looking into the `isLoading` property. Maybe it would be good to add a point to the readme how this component is intended to work with remote data?

**Comment by miguelcobain** [comment]
I'm open to suggestions.
