### ISSUE TITLE
Selection issue

### ISSUE THREAD

**Issue by karellm** [miguelcobain/ember-cli-selectize#26]
Hey, 

My use case a pretty simple, I define my options in an array of objects like so:

```javascript
frequencies = [
    {value: 'annualy',  label: 'Annualy'},
    {value: 'quaterly', label: 'Quaterly'},
    {value: 'monthly',  label: 'Monthly'}
]
```

Then I have a model that has a frequency field. Obviously, I simply want the value, not the entire object from the above frequencies array. So I create a selectize like so:

```javascript
{{ember-selectize
    content=frequencies // this is the above array
    optionValuePath="content.value"
    optionLabelPath="content.label"
    selection=frequency // this is the model frequency
    placeholder="Select a frequency"
}}
```

Selection doesn't work and when I select something, it sets `frequency` to the full object {}, not the value alone. This is very counter-intuitive to me since I can't think of any use case where you'd want the entire object. Am I doing something wrong? I'd like to avoid creating virtual attributes simply to work with selectize.

Thanks!

**Comment by karellm** [comment]
The art of answering your own question. Simply use `value` instead of `selection`: 

```javascript
{{ember-selectize
    content=selectOptions.frequencies
    optionValuePath="content.value"
    optionLabelPath="content.label"
    value=frequency
    placeholder="Select a frequency"
}}
```

**Comment by miguelcobain** [comment]
> This is very counter-intuitive to me since I can't think of any use case where you'd want the entire object.
Imagine a model relationship, i.e A User - Role where you want to set a Role object on the User.

For more info on `value` and `selection` check the README and #16.

**Comment by karellm** [comment]
Makes sense, thanks!
