### ISSUE TITLE
optionTemplate and optionView not working anymore

### ISSUE THREAD

**Issue by saarangsoltani** [miguelcobain/ember-cli-selectize#29]
``optionTemplate``,``itemTemplate``,``optionCreateTemplate``,``optgroupHeaderTemplate``,``optgroupTemplate``, ``optionView``,``itemView``,``optionCreateView``,``optgroupHeaderView`` and ``optgroupView``

basically using the above-mentioned properties would cause ember throw an error saying ``view.renderToBuffer() is no longer available``. we should find a workaround for this. Maybe get the string representation of rendered view this way:
```javascript
      _getStringFromView:function(view){
           view.createElement();
           return view.element.outerHTML
      },
```
i can get it done if you want

**Comment by salzhrani** [comment]
I suggest using the function variants, currently rendering templates and views in an ad hoc manner is not exposed in a public API.

**Comment by saarangsoltani** [comment]
well ``createElement()`` is part of the public API : http://emberjs.com/api/classes/Ember.View.html#method_createElement

**Comment by salzhrani** [comment]
[the last two paragraphs](https://github.com/emberjs/ember.js/issues/5534#issuecomment-60527838).  But Even if you get it running all you get back is the html of the view and not any behaviours attached to the view, so it could be less efficient. you can try if you like.

**Comment by netcurate** [comment]
Well, there is another issue with function variants. Check this out.

{{ember-selectize
                content=controller.items
                optionValuePath="content.id"
                optionLabelPath="content.selectize_display"
                sortField= "display_name"
                optionFunction=controller.offn
                itemFunction=controller.itmf
... }}

Now in controller, you have this:

offn: function(i){

        if (!Ember.isEmpty(i.label)){
            return i.label.toHTML();
        }
    },
    itmf: function(i){
        if (!Ember.isEmpty(i.label)) {
            return i.label.toHTML();
        }
    },

So far all is ok. As you can see content is binded to controller.items ... but if this items is changed and you come back second time, the functions do not pick up the added items. 

I tried making these properties dependent on items, but that means when a new item is added offn and itmf gets called and they do not have values for "i" parameter. 

What is wrong here?

**Comment by miguelcobain** [comment]
If only selectize could support DOM nodes... : https://github.com/brianreavis/selectize.js/pull/617

**Comment by miguelcobain** [comment]
New progress, maybe: https://github.com/emberjs/ember.js/issues/5534#issuecomment-81818954

**Comment by saarangsoltani** [comment]
@miguelcobain seems like DOM nodes are now supported ? that pull-request is merged

**Comment by miguelcobain** [comment]
Looks like its still open: https://github.com/brianreavis/selectize.js/pull/617

**Comment by freshabhilash** [comment]
Is there a possibility to have a component render as itemFunction?

    {{some-component text=label}}

**Comment by abhilashlr** [comment]
Is it possible to render component inside the itemFunction?

    {{some-component text='Lorem'}}

**Comment by Ramblurr** [comment]
Rendering a component inside the itemFunction is exactly what I'm looking for, that or using itemView and passing a component, however that doesn't seem to be working right now.

**Comment by topaxi** [comment]
The PR to allow DOM nodes was successfully merged yesterday :+1:

**Comment by miguelcobain** [comment]
I was watching that thread. Great news!
In theory, we can now:
- make ember-cli-selectize install selectize master from bower (not `master` branch, but a fixed sha, of course)
- lookup a component/template and pass selectize the rendered DOM

I accept PR's and can offer some guidance at ember's slack, if needed.

**Comment by miguelcobain** [comment]
Closed by https://github.com/miguelcobain/ember-cli-selectize/commit/47bfcaa9a8470b3f3b845a6e7b64f9272a4cad71

Latest Selectize bower version doesn't include @topaxi's PR yet. Currently using my fork of selectize. Will change to selectize's when it bumps.

**Comment by Ramblurr** [comment]
Awesome news!

Just curious, does this fully support component in the ember way? That is, with actions and computed properties? Or is it a one-time rendering of a component?

**Comment by miguelcobain** [comment]
Yes. Normal components. Bindings, actions, everything.
