### ISSUE TITLE
Inputs overlapping

### ISSUE THREAD

**Issue by ziggurat** [miguelcobain/ember-cli-selectize#3]
Trying to use this component but getting this rather strange look on the UI. For some reason it is showing two inputs, a "normal" input and then the select on top of it:

![overlapping](https://cloud.githubusercontent.com/assets/320557/5478022/49b2e9da-860f-11e4-83a0-8ca38c51ac69.png)

Nothing strange on the component options:

    {{ember-selectize
          content=cilindros
          optionValuePath="content.id"
          optionLabelPath="content.codigo"
          selection=selectedCilindro
          placeholder="Select an option"
        }}

It seems to be related with styling. My app is using ember 1.9, handlebars 2.0, jquery 2.1.2 and bootstrap 3.3.1.

Any ideas?

**Comment by miguelcobain** [comment]
Issue #5 might solve your issue.
You can now configure which theme ember-cli-selectize imports.
