### ISSUE TITLE
Add action for "onSelect"

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-cli-selectize#30]
Let's say I want to trigger some event on the page when the user selects something from the selectize component. Currently, I would have to set an observer on the value that selectize is bound to and fire an action that way. I realize the native ember select view doesn't offer this but it would be nice to have.

**Comment by miguelcobain** [comment]
With the latest Ember motto "actions up bindings down" I think this would be good to have.
However, I still think that binding an observer is better in this case. This way your application would still work if ever change your selectbox library/component.

**Comment by sandstrom** [comment]
I'd say `selected` would be a good primary action, and then secondaries for `create` etc. This would still ensure isolation, since the action name is bound on the 'outside' (i.e. the application would still work if the selectbox component is replaced).

```
{{ember-selectize
  content=controller.countries
  optionValuePath="content.id"
  optionLabelPath="content.name"
  action='countrySelected'
  created='countryCreated'
}}
```

What do you think @miguelcobain, sounds like a good structure?

More on components and events: 
http://emberjs.com/guides/components/sending-actions-from-components-to-your-application/

**Comment by miguelcobain** [comment]
I really like it.

Can you arrange a PR for this? Along with a README update?

**Comment by miguelcobain** [comment]
This is on selectize `0.1.0`.

Check: https://github.com/miguelcobain/ember-cli-selectize#actions

**Comment by SirZach** [comment]
Thanks!!

**Comment by topaxi** [comment]
I just tried this, i can't seem to get it work. If i grep for 'onSelect' through the component source, i get nothing.

**Comment by miguelcobain** [comment]
README is wrong, sorry.

It is sent as the main action.

Just use `action="someAction"`. I guess the action names will be changed soon: https://github.com/miguelcobain/ember-cli-selectize/pull/34#issuecomment-81698302
Please bear with me while I get this up.

**Comment by miguelcobain** [comment]
@topaxi published `0.1.1` with the correct onSelect action. Sorry for the trouble.

**Comment by topaxi** [comment]
Hey no problem :) Thank you very much for reacting so fast :+1:

**Comment by vnazarenko** [comment]
Hi, is there any way to trigger some custom event not on change, but even on select the same option. I use selectize for navigation, and want just to reload page if user try to select the same option.

**Comment by miguelcobain** [comment]
@vnazarenko looking at [selectize events](https://github.com/brianreavis/selectize.js/blob/master/docs/events.md), I don't think we can capture that using selectize API only.
