### ISSUE TITLE
New item added in array doesn't get reflected

### ISSUE THREAD

**Issue by netcurate** [miguelcobain/ember-cli-selectize#31]
After the content=controller.items get binded, if you add a new item to controller.items - it doesn't show up in the dropdown.

How can I force "refresh"?

**Comment by salzhrani** [comment]
It is bound and should update ... how are you adding the new item

**Comment by netcurate** [comment]
Ah well .. I am going to a different screen where item gets added and goes to DB. Then I come back on this screen .. I can see it's getting pulled from DB .. but the newly added item doesn't show up in the select control.

**Comment by salzhrani** [comment]
Are you using `push` or `pushObject` to add items to the array?

**Comment by netcurate** [comment]
Nope. I am getting it from store. Force refresh from DB. Well, earlier I thought since I was using optionFunction .. the issue could be there. But I removed that. It's plain vanilla code. 

Even I am surprised by this behavior.

**Comment by miguelcobain** [comment]
Proof that ember-selectize component works when new item in the array is added: http://emberjs.jsbin.com/lazeqixipe/2/edit?html,js,output

Just click the buttons and check the the options on selectize box changed.
Feel free to adapt this JSBin to illustrate your problem. If you show us a failing JSBin it will be much easier for us to solve your problem.

**Comment by netcurate** [comment]
Yep, I found where the issue. It was with Promise returning before new object added into DB. Sorry for the trouble.

**Comment by talhaobject90** [comment]
the push Object is not working for me 

ember 2.2.0
ember-data 2.1.0 
    "selectize": "miguelcobain/selectize.js#master",




 // in controller file
    createSupplier: function(){
      
      var controller = this;
      var newsupplier = this.store.createRecord('supplier', {
        companyname :this.get('companyname'),
        email :this.get('email'),
        address1 :this.get('address1'),
        address2 :this.get('address2'),
        suburb :this.get('suburb'),
        city :this.get('city'),
        state :this.get('state'),
        country : this.get('country'),
        zipcode :this.get('zipcode')
      });
      
      newsupplier.save().then(function(){
        controller.set('companyname','');
        controller.set('email','');
        controller.set('address1','');
        controller.set('address2','');
        controller.set('suburb','');
        controller.set('city','');
        controller.set('state','');
        controller.set('country','');
        controller.set('zipcode','');

                     controller.get('suppliers').pushObject(newsupplier);  //not working

                     controller.get('suppliers').reload(); // not working

      })
      
      // I tried converting it into arrray(i got it while googling  -- but didn't worked)
      var suppliers = this.get('suppliers').toArray()
       suppliers.addObjects(this.get('suppliers'));
       suppliers.addObject(newsupplier);
       this.set('suppliers', suppliers);
      
      // another way from some forums  --- Didn't worked
       this.get('suppliers').forEach(function(newsupplier) {
         this.get('suppliers').pushObject(newsupplier._internalModel);
       });
      
    }
