### ISSUE TITLE
Duplicate styles applied

### ISSUE THREAD

**Issue by ismyrnow** [miguelcobain/ember-cli-selectize#35]
When using the stylesheets from the `dist` folder in selectize, the themed ones (e.g. bootstrap3) are actually compiled less stylesheets which include the base styles. Including `selectize.css` also just doubles the size of the css getting imported.

Notice how large `selectize.bootstrap3.css` is, and how similar it is to `selectize.css`.
https://github.com/brianreavis/selectize.js/blob/master/dist/css/selectize.bootstrap3.css

**Comment by ismyrnow** [comment]
On further investigation, it seems like perhaps those styles are needed, even though they seem very much like duplicates. I will close this issue for now. Might be something I should take up with the maintainer or selectize.

**Comment by miguelcobain** [comment]
If you ever open any issue, please let us know.

**Comment by ismyrnow** [comment]
On further investigation, the `selectize.xx.css` files do include the base styles.

I'm opening up a PR for this.
