### ISSUE TITLE
Option to deselect

### ISSUE THREAD

**Issue by drewcovi** [miguelcobain/ember-cli-selectize#43]
It appears once an option is set, we lose the ability to deselect it as that "null" value goes away completely.  It appears this should be supported in selectize provided we include a "null" option as the first item.

Is this a bug or am I missing the proper implementation approach?

**Comment by drewcovi** [comment]
Small update: I can see that we have a cursor and can delete the item in the select box, this is a bit or a departure from the norm, it would be nice to have either a button to click or a 'clear' option in the dropdown.

**Comment by drewcovi** [comment]
I'm starting to realize this is a selectize request.

**Comment by miguelcobain** [comment]
I thought so. :)
I use the "remove_button" selectize plugin which should be enabled by default on ember-cli-selectize.

http://brianreavis.github.io/selectize.js/ (tab plugins, section "remove_button").

**Comment by drewcovi** [comment]
hmmm not seeing it enabled by default.... or do you mean included by default?

**Comment by miguelcobain** [comment]
I mean enabled (this plugin only works in multiple selects, i.e when `multiple=true`).

Here is the array:
https://github.com/miguelcobain/ember-cli-selectize/blob/master/addon%2Fcomponents%2Fember-selectize.js#L41

**Comment by drewcovi** [comment]
ah! yes multiselect only :+1:  

thats cool, ill see what we can do for everything else. comparing it to select2 which has a clear button available for single items.

**Comment by miguelcobain** [comment]
That is indeed something related with selectize.
Please link here if you find what you're looking for. Thanks.

**Comment by miguelcobain** [comment]
Just occured to me that a possible workaround might be to use `multiple=true` and `maxItems=1`.
But don't know how that would work. The `selection` property would be an array and you would need the `add` action. So, probably not the ideal solution.

**Comment by drewcovi** [comment]
yeah, im thinking i just throw in a button and just have the action clear out the bound property for now, but it would be nice if somewhere down the road (whether that be in a selectize addon or here) that we have an option to tack on a close button that's right justified.

**Comment by miguelcobain** [comment]
Selectize is quite extensible.
You could try to write a selectize plugin similar to "remove_button".
The plugin could just display an "x" next to the "carret down" symbol.

More info on selectize's extensibility: https://github.com/brianreavis/selectize.js/blob/master/docs/plugins.md

**Comment by Keeo** [comment]
There is plugin for that https://gist.github.com/jumika/abe412f1aa2b24ea86e6, but change does not propagate to ember.

**Comment by miguelcobain** [comment]
@Keeo ember-selectize doesn't update on clear because we're not handling the `clear` event selectize emits: https://github.com/brianreavis/selectize.js/blob/master/docs/events.md

Setting `selection` to `null` on the `clear` event should make that plugin work.

**Comment by Keeo** [comment]
Thanks, do you want PR? Something like this:
```javascript
// component
var options = {
  onClear: Ember.run.bind(this, '_clear')
};

_clear(){
  this.set('selection', null);
},

// initializer
// copy of code above
```

**Comment by miguelcobain** [comment]
A PR for that would be great!
