### ISSUE TITLE
When passing objects as content/selection removing them throws error

### ISSUE THREAD

**Issue by LevelbossMike** [miguelcobain/ember-cli-selectize#44]
Hi!

When passing an array of Objects to the content property (e.g. an array of ember-data models) and using `content` as `optionsValuePath` (e.g. as needed by ember-data when working with relationships) removing an object from the selection throws an error in selectize.

`Uncaught TypeError: $item.attr is not a function` in selectize's [removeItem-method](https://github.com/brianreavis/selectize.js/blob/master/src/selectize.js#L1488)

Because the observers that trigger this code are also triggered on `willDestroyElement` this also fails when removing the component from the DOM.

This makes this addon basically unusable for working with ember-data relationships which is very unfortunate because ember.select is also not working for ember-data relationships ;).

I am happy to help with solving this issue but I think input from @miguelcobain would be very useful as I am not really familiar with selectize or ember-cli-selectize.

Any idea what's the problem here?

And of course thanks for this great addon!

**Comment by miguelcobain** [comment]
The correct property name is `optionValuePath` and not `optionsValuePath`.
Please confirm if this was the problem.

Ember data objects should definitely work.

**Comment by LevelbossMike** [comment]
Sorry that was a typo. I am using `optionValuePath` and it's really not working :(.

**Comment by miguelcobain** [comment]
What's does the template you're using to render ember-selectize looks like?

**Comment by LevelbossMike** [comment]
just update.

**Comment by miguelcobain** [comment]
The problem is probably related with `optionValuePath='content'`.

Selectize requires us to have unique identifiers for each of our options. What were you really trying to accomplish with `optionValuePath='content'`?

**Comment by LevelbossMike** [comment]
I want to pass the Ember data model. That's required when working with
relationships as Ember data will take care of serialzing this into the
correct JSON representation.
Am 18.03.2015 16:07 schrieb "Miguel Andrade" <notifications@github.com>:

**Comment by miguelcobain** [comment]
The Ember data models are already being passed through `content=tags`.
Also, when `multiple=true`, then `selection` will be an array filled with objects from `tags`.

Isn't this what your aiming at?

**Comment by LevelbossMike** [comment]
Aaah! Thanks a lot. valueOptionPath 'content.id' works correctly. :+1: Thanks for helping out!

**Comment by LevelbossMike** [comment]
Oh and I also noticed that I am apparently too dumb to read the documentation correctly because it's basically in the documentation how to do this. Sorry for bothering and thanks for your help again.
