### ISSUE TITLE
How to add new items

### ISSUE THREAD

**Issue by sirvine** [miguelcobain/ember-cli-selectize#45]
The first [demo](http://brianreavis.github.io/selectize.js/) shows an example of a multi-select that supports adding new items.  Two questions:

1.  What's the API for implementing this?  I tried setting `create=true` on the component.
2.  Is this also available for single-selects?

**Comment by miguelcobain** [comment]
As stated on the actions section on the readme:
> create-item - sent when the user creates a tag. The text is sent as a parameter.

Example with single selects:
```handlebars
{{ember-selectize
  content=controller.items
  optionValuePath="content.id"
  optionLabelPath="content.name"
  selection=model.item
  placeholder="Select an item"
  create-item="anActionOnMyController" }}
```
```javascript
export default Ember.Controller.extend({
  actions: {
    anActionOnMyController: function(text) {
      var obj = //create the desired object with `text` here
      this.get('items').addObject(obj);
      //if you need to select the newly created option:
      this.set('model.item', obj);
    }
  }
});
```

Please, report if you find any issues.

**Comment by sirvine** [comment]
Thanks for the quick feedback. That does indeed work.  I guess I was a little confused by the docs, but this sorted me out.

**Comment by miguelcobain** [comment]
Probably because that demo is old. It uses an old version of ember-selectize.

We need to address #18 asap...

**Comment by ganeshfreshdesk** [comment]
Following above method, new tag value (i.e., say 'test' ) is pushed to content and selection but it is not inserted into the dom. Instead it shown in drop down to select again.
console.log(this.get('selection')) gives:  ["test", Object, __ember_meta__: Object]
'Object' item is selected form the drop down. In what way 'Object' item and "test" item in selection array is different?
2.onItemAdd, onItemRemove : options avalilable in selectize Ember.run.bind to default functions. How to access them to add new item just like how default selectize does? 
I am bit stuck !
