### ISSUE TITLE
Feature Request: Better Handling of Async Data

### ISSUE THREAD

**Issue by drewcovi** [miguelcobain/ember-cli-selectize#46]
Right now if I want to lazy load my data, any selected items are showing up as 'undefined' until that relationship resolves.  It would be nice to have the option to use an empty string instead so values elegantly appear, and when re-visiting a route rendering can appear far quicker even if options are updated in the background.

**Comment by drewcovi** [comment]
and just like that I found the loading option :)

**Comment by miguelcobain** [comment]
How did you solve the undefined label issue?

**Comment by drewcovi** [comment]
I just leveraged the loading class to hide the entire thing until it's done. Not working terribly well for Multiselect. Probably due to me binding to the value instead of the options. Still working on it.

**Comment by miguelcobain** [comment]
I think there is a simple fix that should get into ember-selectize:
If the label is falsy, pass an empty string to selectize. The label will be updated later because we set up an observer on it.

**Comment by drewcovi** [comment]
I'm all for that too :)

**Comment by drewcovi** [comment]
:+1:On Sat, Mar 28, 2015 at 9:18 AM,  Miguel Andrade <notifications@github.com> wrote:            Closed #46 via 32ef4da.

**Comment by drewcovi** [comment]
@miguelcobain does this also handle multiselect elegantly by setting the item count to null (0) as well? or will this populate with a number of empty pills?

**Comment by miguelcobain** [comment]
If the label is falsy, it will add an item normally to selectize.
We expect that label to eventually change.

Another possible approach would be to *only* insert into selectize **if** the label isn't falsy.
I'm not really sure which approach is better.

**Comment by drewcovi** [comment]
The latter would be a hell of a lot prettier :)

**Comment by drewcovi** [comment]
Ultimately the goal would be to avoid the container jumping around as the labels fill.

**Comment by miguelcobain** [comment]
Should be working now. :)
Also published `0.3.1`.

**Comment by drewcovi** [comment]
I'm you're biggest fan today.

**Comment by miguelcobain** [comment]
Tomorrow I may be yours. :+1: 
Thanks for your reports and issue.

**Comment by drewcovi** [comment]
Sorry to resurrect this ticket, I'm seeing some very strange behavior on async items that happen to only have one option...

I've been digging around as best I can, but it seems under the circumstance of only one item, contentArrayDidChange is not firing at all, and thus addLabelObserver is not added...

strangely though _labelDidChange is still mysteriously triggering anyway... it baffles the mind.

**Comment by miguelcobain** [comment]
The test is here: https://github.com/miguelcobain/ember-cli-selectize/blob/master/tests%2Funit%2Fcomponents%2Fember-selectize-test.js#L443

Providing a failing test would be the best way to tackle this.
Can you?

**Comment by drewcovi** [comment]
Totally will. Thanks!
