### ISSUE TITLE
Multiple select with create-item not updating selection

### ISSUE THREAD

**Issue by sirvine** [miguelcobain/ember-cli-selectize#49]
I have the following ember-selectize component:

    {{ember-selectize placeholder="Choose products..."
                  content=controllers.products.model
                  selection=controllers.cycle.tempProducts
                  optionValuePath="content.id"
                  optionLabelPath="content.name"
                  multiple=true
                  create-item="createNewProduct"}}

I can confirm that `createNewProduct` is creating a new object and adding it to the content array, and is also being added to the selection array. However, the new item does not appear in the ember-selectize input.

Update: I should also add that the newly-created object does not appear in either the input as a selection or in the dropdown as part of the content.

**Comment by miguelcobain** [comment]
Show us how you're adding to the arrays.

**Comment by sirvine** [comment]
@miguelcobain Looks like I was running 0.3.0.  Bumped to 0.3.1 and it's working now.  I'll close this.
