### ISSUE TITLE
optgroup work?

### ISSUE THREAD

**Issue by knownasilya** [miguelcobain/ember-cli-selectize#50]
I can't get `optgroup` field to work correctly. I get only on item, and it's the first group; no other groups show up.

```js
// data
{
  name: 'one',
  optgroup: 'group1'
}
```
```hbs
{{ember-selectize content=specifics
  multiple=true
  optgroupLabelField='optgroup'
  optgroupValueField='optgroup'
  optionLabelPath='content.name'
  selection=selectedSpecifics
  class='form-control'}}
```

**Comment by miguelcobain** [comment]
Selectize Option Groups aren't implemented. :disappointed:

**Comment by knownasilya** [comment]
:cry:

**Comment by NotSqrt** [comment]
:+1: I would be very happy to see this implemented !!

**Comment by miguelcobain** [comment]
Let's decide on an API for this.
Following Ember.Select, supposing we want to show a list of posts grouped by their category, it would be:
```handlebars
{{ember-selectize
  content=posts
  selection=selectedPosts
  optionGroupPath="category"
  optionValuePath="content.id"
  optionLabelPath="content.title"}}
```

An example post would be:
```javascript
{
  id: 1,
  category: 'A string',
  title: 'This title will appear on select'
}
```

I would be fine with this.

**Comment by NotSqrt** [comment]
For full functionality, you need:
* optgroups : list of group objects
* optgroupField which is the path to the property of the items that should be used for grouping (your optionGroupPath)
* optgroupValueField and optgroupLabelField that are the paths to the properties of the optgroups items to be used as value and label.

**Comment by miguelcobain** [comment]
Ember.Select doesn't do that.
Your suggestion allows to have a separate array of optgroups. Is that really necessary?
We can derive all the needed optgroups from `optionGroupPath`.

Example:
```javascript
posts.mapBy('category')
// this could return ['category 1', 'category 2', 'category 3']
```

If you're using relationships in ember-data, no problem:
```javascript
posts.mapBy('category.name')
// this could return ['category 1', 'category 2', 'category 3']
```
```handlebars
{{ember-selectize
  content=posts
  selection=selectedPosts
  optionGroupPath="category.name"
  optionValuePath="content.id"
  optionLabelPath="content.title"}}
```

I'm not seeing any advantage of your suggestion vs this core Ember.Select's API.
Perhaps you can illustrate me that.

**Comment by NotSqrt** [comment]
Your proposed design is good.
There's just a need to sort the groups in a specific order.

**Comment by NotSqrt** [comment]
How wrong is the README when it mentions optgroupFunction and other optgroup features ?

**Comment by miguelcobain** [comment]
Well, the optgroupFunction option is indeed passed to to selectize. However, since you can't use optgroups, it makes them pretty useless.

**Comment by karellm** [comment]
I'm not familiar with this component or if it would be easy, but why not something [like](https://gist.github.com/ykessler/3349960)? Obviously here, `zones` is too specific but you get the idea.

```javascript
{
  "Category 1": [
    {value: "foo", label: "Foo"}
  ]
}
```

OR

```javascript
[
  {
    group: "Category 1",
    content: [
      {value: "foo", label: "Foo"}
    ]
  }
]
```

**Comment by miguelcobain** [comment]
We will folow Ember Select's approach, which is really flexible:

## `#1` scenario ##
Set `optionGroupPath` to a path for a property to group for.
Example:
```javascript
[
  {
    id: 1,
    category: 'Nature',
    title: 'This title will appear on select'
  },
  {
    id: 2,
    category: 'Nature',
    title: 'This title will appear on select'
  },
  {
    id: 3,
    category: 'Another category',
    title: 'This title will appear on select'
  },
  //...
]
```

`optionGroupPath` would be `content.category`, which would group items according to that property automatically.

like

```handlebars
{{ember selectize optionGroupPath="content.category"}}
```

## `#2` scenario ##

If you prefer you can group your items yourself and pass them to ember selectize.
Just set the property `groupedContent` to an array with the following format:

```javascript
[
  {
    label: 'Nature',
    content: [
      {
        id: 1,
        category: 'Nature',
        title: 'This title will appear on select'
      },
      {
        id: 2,
        category: 'Nature',
        title: 'This title will appear on select'
      }
    ]
  },
  {
    label: 'Another category',
    content: [
      //...
    ]
  },
//...
]
```
and in your template

```handlebars
{{ember selectize groupedContent=someArray}}
```

**Comment by knownasilya** [comment]
I like it.

**Comment by karellm** [comment]
@miguelcobain in #2 inside of `content` do we still need to set the `category`? Other than that it looks good!

**Comment by miguelcobain** [comment]
@karellm we don't to do that. Grouping information is already provided by data structure. :)

**Comment by karellm** [comment]
@miguelcobain That was my thought but you left it in your example, hence my question :)

**Comment by miguelcobain** [comment]
Edited to avoid confusion.

**Comment by miguelcobain** [comment]
Here's a first try at `optgroups` branch https://github.com/miguelcobain/ember-cli-selectize/commit/318f9d454feec3d6f2859103d231b1e923667a94

#1 scenario is working. #2 scenario is working but changes to each `content` property aren't observed.
Also, tests and README updates are missing.

If anyone wants to help or give some feedback, that's the branch to use.

**Comment by ashrafhasson** [comment]
Thanks @miguelcobain , I've actually got it complaining that it can't find ember-new-computed after installing from the `optgroups` branch 318f9d4
```javascript
Error: Could not find module `ember-new-computed` imported from `ember-cli-selectize/components/ember-selectize`
```

**Comment by miguelcobain** [comment]
@ashrafhasson That branch was fixed and merged with master. Should be working now.

**Comment by mariuserik** [comment]
Hi.

The categories are not appearing. I'm using optgroup branch, and that is my component call:

```javascript
{{ember-selectize
  content=columnsForSelect
  optionValuePath="content.id"
  optionLabelPath="content.label"
  optionGroupPath="content.category"
  selection=selected.columns
  multiple=true
  placeholder="Select an item"
  plugins="remove_button"
}}
```
I've checked the content and it is correct, it contains a category, id, label.

The columns just appear normally, without the category over, It should appear 10 categories.

Someone have the same problem? maybe is something with the other parameters I send to the component?

BR,

Marius

**Comment by halfdan** [comment]
Can we get this merged? Master was merged into the `optgroups` branch but sadly not the other way around. It would be great it this could be released soon.

**Comment by miguelcobain** [comment]
You're using this branch?

**Comment by miguelcobain** [comment]
master changes have been merged with this branch until I find myself some time to handle scenario 2.

**Comment by miguelcobain** [comment]
Since version `0.4.0` ember-cli-selectize supports optgroups and is Ember 2.0 compatible. Than you all.
