### ISSUE TITLE
Error on install ember-cli v0.2.3: ember generate requires an entity name to be specified

### ISSUE THREAD

**Issue by varblob** [miguelcobain/ember-cli-selectize#51]
ember install ember-cli-selectize
version: 0.2.3
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/brianreavis/selectize.js.git#0.12.0
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by varblob** [comment]
Probably related to 0.2.3 actually.  

https://github.com/ember-cli/ember-cli/issues/3829

I'm gonna close this for now.

**Comment by sedovalx** [comment]
Hi! I have exactly the same promlem. Can you give me a tip how to fix it?
