### ISSUE TITLE
Possible to get events

### ISSUE THREAD

**Issue by Frozenfire92** [miguelcobain/ember-cli-selectize#6]
Great plugin! Thanks for the effort, works flawlessly out of the box

I'm wondering if it is possible to get the [events](https://github.com/brianreavis/selectize.js/blob/master/docs/events.md#list-of-events) callback information.

My use case is I have a manage route where there are multiple elements that may or may not be there in the db, and this list could be added to. However these elements aren't directly on the model but computed properties based on the relations in the database. When I remove an element from this list I need to know about it so I can update the element in the database (as this is a computed property on the model)

I hope that use case is clear, if not let me know

**Comment by miguelcobain** [comment]
@Frozenfire92 I'm afraid I didn't fully understand your use case.

However, here are my thoughts on providing support for selectize events:
some of the events selectize exposes are "data-related". This may make sense for simple "jquery-based" apps. But here, we are using selectize as a view layer.
What I mean is that you should be able to handle these data related events *outside* of ember-selectize/selectize.
Ember-selectize will reflect whatever is in your array and selection, that is its main purpose.

Please try to make your use case more clear, ideally using an example JSBin:  http://emberjs.jsbin.com/

I'm here to help!

**Comment by Frozenfire92** [comment]
Ok, I was afraid I wasn't being very clear.

Essentially I have an `organization` with may `people`. However the people aren't directly part of the organization's model in the db. Rather they are related based on the `people`'s organization key in their  own entry in the db. Essentially I want to use selectize to add/remove people from the organization. However when removing I need to know about it so I can update that person's organization key on their model.

Does that clear things up?

Thank you!

**Comment by miguelcobain** [comment]
Ok, it is clear now. You're using a multiple select, right?
Adding and removing a person from that select, sets or removes a specific organization id, right?

**Comment by miguelcobain** [comment]
Here is what I would do.

Controller:
```javascript
exports default Ember.Controller.extend({
    selectedPeople:[],
    setObservers:function(){
        this.get('selectedPeople').addArrayObserver(this,{
            willChange: 'selectedPeopleWillChange',
            didChange: 'selectedPeopleDidChange'
        });
    }.on('init'),
    //Will trigger when one or more people are removed
    selectedPeopleWillChange:function(array, idx, removedCount){
        for (var i = idx; i < idx + removedCount; i++) {
            //acess removed elements here through `array.objectAt(i);`
            //unset your organization key here
        }
    },
    //Will trigger when one or more people are added
    selectedPeopleDidChange:function(array, idx, removedCount, addedCount){
        for (var i = idx; i < idx + addedCount; i++) {
            //acess added elements here through `array.objectAt(i);`
            //set your organization key here
        }
    },
});
```
And its template:
```handlebars
{{ember-selectize
  content=controller.people
  optionValuePath="content.id"
  optionLabelPath="content.name"
  selection=model.selectedPeople
  multiple=true
  placeholder="Select people" }}
```

I think this is the kind of logic that belongs in the controller. We could use selectize's events, yes. But imagine that someday you want to revert back to vanilla selects or any other selectbox library?
This could would become untouched.

I like to think focused on the data. The view must just do its job and represent that.
**I shouldn't need the view to know when my data changes.**

Let me know if this worked for you.

**Comment by Frozenfire92** [comment]
>Ok, it is clear now. You're using a multiple select, right?
Adding and removing a person from that select, sets or removes a specific organization id, right?

Correct and correct.

I won't have a chance to work on the code for a few days but I will let you know how it goes. Thank you very much for your help :smile:
