### ISSUE TITLE
How do i use without "import computed from 'ember-new-computed" in ember-selectize component

### ISSUE THREAD

**Issue by vinothwindows47** [miguelcobain/ember-cli-selectize#60]

**Comment by vinothwindows47** [comment]
I don't want ember-new-computed

**Comment by vinothwindows47** [comment]
Can I do default ember computed

**Comment by salzhrani** [comment]
What are your concerns regarding ember-new-computed ?

**Comment by miguelcobain** [comment]
Closed due to inactivity and lack of information.
Reopen if things get more clear.

**Comment by miguelcobain** [comment]
@salzhrani Is it possible that this is forcing people to use the new computed syntax in consuming apps?

**Comment by salzhrani** [comment]
It is a polyfill used internally. Doesn't affect users code AFAIK.
