### ISSUE TITLE
Could not find module `ember-new-computed`

### ISSUE THREAD

**Issue by igorrKurr** [miguelcobain/ember-cli-selectize#69]
After my issue #68 (thanks for quick solving!) i've updated  to 0.3.2 and had an error:

```
Uncaught Error: Could not find module `ember-new-computed` imported from `ember-cli-selectize/components/ember-selectize`
```

I guess i can be connected to ember-cli so, i leave here its version.
I use ember-cli@0.2.5 and ember@1.13.0-beta.1

**Comment by miguelcobain** [comment]
Looks like `ember-new-computed` module can't be found.
Running `npm install` solves the problem?

Sometimes npm freaks out. Try deleting `node_modules/` and running `npm install` again.

**Comment by igorrKurr** [comment]
I did this, even with npm cache clear, but no result...
It seems to me that problem is in `ember-new-computed` package itself, so i'm going to open issue there.

**Comment by Frozenfire92** [comment]
+1 ran into the same issue this morning, neither npm install, npm install ember-new-computed worked (with clearing `node/modules/`)

**Comment by bdvholmes** [comment]
Introduced in #54, is there any chance we can just use a newer version of ember and remove the need for ember-new-computed.

**Comment by miguelcobain** [comment]
I've noticed that we weren't using any getter and setter computed property. So the old syntax for getter computed properties is the same as the new one.
We don't need `ember-new-computed`.

Also release 0.3.3 version. The problem should be fixed.

**Comment by Frozenfire92** [comment]
This fixed it thanks :)

Until npm updates here is the way to put it in your package.json for anyone lazy 

`"ember-cli-selectize": "git://github.com/miguelcobain/ember-cli-selectize.git#v0.3.3",`

**Comment by miguelcobain** [comment]
@Frozenfire92 It should be on npm now. My mistake. :+1:

**Comment by igorrKurr** [comment]
Thanks! :+1:
