### ISSUE TITLE
onItemAdd, onItemRemove : How to use it?

### ISSUE THREAD

**Issue by ganeshfreshdesk** [miguelcobain/ember-cli-selectize#73]
onItemAdd: Ember.run.bind(this, '_onItemAdd'),
onItemRemove: Ember.run.bind(this, '_onItemRemove'),
onType: Ember.run.bind(this, '_onType')

How to make use of this options to insert new selection, remove selection?

**Comment by miguelcobain** [comment]
To insert a new option simply push another item to the `content` array.
To set a new selection simply set the `selection` or `value` property (to an array or item, depending if multiple is true or not).

Refer to the README to understand the difference between `selection` and `value`.
Refer to the dummy test app for examples.
