### ISSUE TITLE
Loading content from remote source

### ISSUE THREAD

**Issue by colinhoernig** [miguelcobain/ember-cli-selectize#81]
Hi Miguel.  Thank you for the great Selectize addon.

I'm looking to load selectize options from a remove source in order to build autocomplete functionality based on remote data.  [Here is an example](https://github.com/brianreavis/selectize.js/blob/master/examples/movies.html) of what I'd like to achieve from the Selectize.js docs.  This functionality does not seem to be implemented within the ember-cli-selectize addon.

I did attempt to use the `update-filter` action to try and build the `content` object array when a user types in the input field, but did not have much luck.

I'd love to see an example of loading remote data as a source for the selectize control, if possible.

Thank you!

**Comment by miguelcobain** [comment]
I'll show you an example of my own.

Controller:
```js
export default Ember.Controller.extend({

  streets: function() {
    //fetch streets here. You'll probably want to include your model's street here as well
    var streetFilter = this.get('streetFilter');

    return DS.PromiseArray.create({
      //do whatever you need to remotely fetch the models, based on the filter
      promise: this.store.find('street', { name: streetFilter })
    });
  }.property('streetFilter', 'model.street'),

  actions: {
    streetFilterUpdate(str) {
      this.set('streetFilter', str);
    }
  }
});
```
Template:
```hbs
{{ember-selectize content=streets selection=model.place
  update-filter="streetFilterUpdate" loading=streets.isPending}}
```

A loading class will be applied to selectize while the loading is happening.
