### ISSUE TITLE
How does this lib handle async items

### ISSUE THREAD

**Issue by billybonks** [miguelcobain/ember-cli-selectize#84]
lets say you want to load items based on a `store.find` call

I have tried :
* set the target variable with the new content when the promise resolves
* set the target variable to empty array then merge it with the result of the promise

**Comment by miguelcobain** [comment]
Can you share your template/code?

I just do `content=property`. Where property is a result of a find call. But I wait for them to resolve (`model` hook).
Alternatively `content=property.content` may also work if the promise didn't resolve yet.

**Comment by billybonks** [comment]
```
import Ember from 'ember';

export default Ember.Component.extend({
  willInsertElement:function(){
    this.set('wars',this.get('store').find('wars'))
  }
});
```

```
{{ember-selectize content=wars optionLabelPath="content.name" create-item="create" multiple=true selection=selection placeholder="Select an item" }}
```

**Comment by miguelcobain** [comment]
Ember-cli-selectize is not adding items to selectize which labels are falsy. Do the contents have a valid `name` property?

What does the following template print? (put it next to the `{{ember-selectize}}` component call, for example).
```hbs
<ul>
  {{#each wars as |war|}}
    <li>{{war.name}}</li>
  {{else}}
    <li>No wars available.</li>
  {{/each}}
</ul>
```

**Comment by miguelcobain** [comment]
Offtopic:
I don't really like to access the store from a component. Many people, including me, see it as an anti-pattern. The store isn't even injected in the components, for example.
I would just try to pass the `wars` array from whatever the context is of the component you're building (probably a route or controller).

**Comment by billybonks** [comment]
besides the off topic which is an entirely different discussion :)

`Alternatively content=property.content may also work if the promise didn't resolve yet`

the each errors because wars is a promise. i was testing out your afore mentioned approach.

another use cause would be:
 "execute a search query when user types that fetches data from an api" which is possible with the base selectize plugin.

**Comment by miguelcobain** [comment]
> another use cause would be:
"execute a search query when user types that fetches data from an api" which is possible with the base selectize plugin.

This has been discussed previously: https://github.com/miguelcobain/ember-cli-selectize/issues/81#issuecomment-117057339

**Comment by billybonks** [comment]
looks good :+1:
