### ISSUE TITLE
Ember 2.0 Support

### ISSUE THREAD

**Issue by thehydroimpulse** [miguelcobain/ember-cli-selectize#86]
Testing on canary results in the following error being reported:

```
Uncaught TypeError: Ember.default.beforeObserver is not a function
(anonymous function)	@	ember-selectize.js:298
mod.state	@	loader.js:141
tryFinally	@	loader.js:21
requireModule	@	loader.js:139
requireFrom	@	loader.js:112
reify	@	loader.js:97
mod.state	@	loader.js:140
tryFinally	@	loader.js:21
requireModule	@	loader.js:139
Ember.DefaultResolver.extend._extractDefaultExport	@	ember-resolver.js:367
resolveOther	@	ember-resolver.js:109
```

http://emberjs.com/deprecations/v1.x/#toc_beforeobserver

I can send a patch if you'd like.

**Comment by miguelcobain** [comment]
I would love a patch.
I confess I didn't understand how the code you linked to can replace beforeObservers, but I'm sure that's just me. :anguished:

**Comment by marcemira** [comment]
:+1: Please fix this :3

**Comment by miguelcobain** [comment]
Ember 1.13.4 introduced a bug which basically removed beforeObservers. That makes ember-cli-selectize to fail.

Waiting for this fix: https://github.com/emberjs/ember.js/pull/11744

**Comment by rwjblue** [comment]
I just merged that PR fixing the `deprecateFunc` behavior, and pulled into release branch.  Folks can use `bower install --save ember#release` until 1.13.5 is released (which should be a few days).

**Comment by miguelcobain** [comment]
ember-try is now passing, thanks!
```
------ RESULTS ------

default: PASS
ember-release: PASS
ember-beta: PASS
ember-canary: PASS
```

Is it supposed to be passing in ember canary/beta, since I'm using `beforeObserver`?
I thought Ember 2.0 would remove all deprecated functionality.

**Comment by grapho** [comment]
Where are we with this issue?  Do we still need a solution to replace the (2) uses of beforeObserver?  I am working on my local version to see what i can do to fix, and will PR if no one posts a fix before me.

**Comment by miguelcobain** [comment]
Yes, we still need to get rid of beforeObservers.
A PR for that would be great! I'm a bit short on time ATM.

**Comment by grapho** [comment]
well I will work on it today. hopefully i can come with a solution soon.. because the alternative is to rollback and wait.. ugk

**Comment by miguelcobain** [comment]
Fixed on https://github.com/miguelcobain/ember-cli-selectize/commit/1fbfaa37376b2db9f33334b2eea701369453f25c

Latest version should be Ember 2.0 compatible.
