### ISSUE TITLE
OptionValuePath not the value returned

### ISSUE THREAD

**Issue by JKGisMe** [miguelcobain/ember-cli-selectize#90]
I apologize if I've overlooked something but when you set an option value path, I would think you are setting the value that option should be returned as. But if you have something like:

```javascript
colors: [
  {id: 0, name: 'red'},
  {id: 1, name: 'blue'},
]
```
and set 
```handlebars
{{ember-selectize
    content=colors
    optionValuePath='content.id'
    optionLabelPath='content.name'}}
```

The returned value upon selection is the entire object `{id:0, name: 'red'}` not just '0'. This is definitely valuable behavior in some situations like for related records. But what if you just want to return '0'? It also seems to have trouble reading the pre-existing selections in this situation as well.

**Comment by miguelcobain** [comment]
What do you mean by "value returned"? Returned from where?

**Comment by JKGisMe** [comment]
From ember-selectize. 

I didn't see, or probably more likely, understand the distinction between `value=someProp` and `selection=someProp`. 'value' is certainly the one I want for these situations. 

I guess for multiple mode I need two other computed properties. one to set to selection and to watch the model's array of ids for changes and convert them into objects and one to watch what's returned by selectize, convert them to ids and set the model's array of ids.

**Comment by miguelcobain** [comment]
Basically `value` is the `optionValuePath` of `selection`.

Like the README states for `value`:
> It is not currently supported in multiple selection mode.

**Comment by JKGisMe** [comment]
Yes, that's why I was thinking about having the two other computed properties to adapt `selection` to work. 

I think I just overlooked `value` initially because it's not in the example hbs code and I didn't really understand the distinction at first so I just went with what was in the example code. Thanks for helping point it out. :)
