### ISSUE TITLE
A helper named 'ember-selectize' could not be found

### ISSUE THREAD

**Issue by IAmJulianAcosta** [miguelcobain/ember-cli-selectize#94]
Hi, I'm trying to use the addon, but I'm getting this error:

Uncaught Error: Assertion Failed: A helper named 'ember-selectize' could not be found

test.hbs:

```
{{ember-selectize placeholder="Select an item" }}
```

I don't know what I'm missing, should I import something before using the addon? Thank you

**Comment by miguelcobain** [comment]
The installation process is simple, just run `ember install ember-cli-selectize`.
I'll try to reproduce this problem.

**Comment by miguelcobain** [comment]
Which ember-cli version you're using?

**Comment by JDillon522** [comment]
I get the same error. I'm on ember-cli 1.13.8

**Comment by beverlyguillermo** [comment]
I am also running ember-cli 1.13.8 -- and after I ran `ember generate ember-cli-selectize`, it started working for me.

**Comment by IAmJulianAcosta** [comment]
I fixed it updating to ember 2.1 with 1.13.8
