### ISSUE TITLE
Single selection adds invisible remove

### ISSUE THREAD

**Issue by btecu** [miguelcobain/ember-cli-selectize#95]
On the demo page, if you select a value under the single selection and then click on it to remove, the cursor is 24 pixels to the right.

That's because when you have multiple items, they have to be spaced apart.
I think having a visible remove (X on the right side) for a single item would be nice, but the issue here is that is adding an invisible remove button causing the space.

**Comment by miguelcobain** [comment]
@btecu This addon just proxies everything to selectize. That's a selectize issue. Selectize is not maintained anymore, though. :(

**Comment by btecu** [comment]
I don't think it's a selectize issue. You can try their demo and you'll see this does not happen.

**Comment by miguelcobain** [comment]
@btecu That demo is old. It's from the early days when ember-selectize wasn't an ember-cli-addon.
Meanwhile, selectize's styles corrected that.

Related with #18.
Still didn't have the time to come up with an updated demo app.

**Comment by btecu** [comment]
I'm using the latest version of ember-cli-selectize and I have the same issue, so I don't think it's just the demo page.
